name: 'C++ CI'

on:
  push:
    branches:
      - "rel/**"
      - "!rel/**/**"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Variables
        id: variables
        run: |
          branch_cut_name=$(echo ${{ github.ref_name }} | sed 's/.*://')
          echo "Project name will be set by cut name of current branch $branch_cut_name"
      - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
      - run: cmake . -DPROJECT_NAME=${{ steps.variables.branch_cut_name }} -DPATCH_VERSION=${{ github.run_number }} -DWITH_BOOST_TEST=ON
      - run: cmake --build .
      - run: cmake --build . --target test
      - run: cmake --build . --target package
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.${{ github.run_number }}
          release_name: Rel v0.0.${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.variables.branch_cut_name }}-0.0.${{ github.run_number }}-Linux.deb
          asset_name: ${{ steps.variables.branch_cut_name }}-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
